default_hir_kind = "Internal"

[[text_tokens]]
name = "Text_fn"
literal = "fn"
hir_kind = "Text"

[[text_tokens]]
name = "Text_LPAREN"
literal = "("
hir_kind = "Text"

[[text_tokens]]
name = "Text_RPAREN"
literal = ")"
hir_kind = "Text"

[[text_tokens]]
name = "Text_LBRACE"
literal = "{"
hir_kind = "Text"

[[text_tokens]]
name = "Text_RBRACE"
literal = "}"
hir_kind = "Text"

[[text_tokens]]
name = "Text_let"
literal = "let"
hir_kind = "Text"

[[text_tokens]]
name = "Text_EQ"
literal = "="
hir_kind = "Text"

[[text_tokens]]
name = "Text_SEMI"
literal = ";"
hir_kind = "Text"

[[text_tokens]]
name = "Text_COLON"
literal = ":"
hir_kind = "Text"

[[text_tokens]]
name = "Text_COMMA"
literal = ","
hir_kind = "Text"

[[text_tokens]]
name = "Text_ARROW"
literal = "->"
hir_kind = "Text"

[[nodes]]
ts_name = "integer_literal"
hir_kind = "Text"

[[nodes]]
ts_name = "type_identifier"
hir_kind = "Identifier"

[[nodes]]
ts_name = "scoped_identifier"
hir_kind = "Identifier"

[[nodes]]
ts_name = "field_identifier"
hir_kind = "Identifier"

[[nodes]]
ts_name = "identifier"
hir_kind = "Identifier"

[[nodes]]
ts_name = "parameter"

[[nodes]]
ts_name = "self_parameter"

[[nodes]]
ts_name = "parameters"

[[nodes]]
ts_name = "let_declaration"

[[nodes]]
ts_name = "field_declaration"
block_kind = "Field"

[[nodes]]
ts_name = "block"
hir_kind = "Scope"
block_kind = "Scope"

[[nodes]]
ts_name = "source_file"
hir_kind = "File"
block_kind = "Root"

[[nodes]]
ts_name = "mod_item"
hir_kind = "Scope"
block_kind = "Scope"

[[nodes]]
ts_name = "struct_item"
hir_kind = "Scope"
block_kind = "Class"

[[nodes]]
ts_name = "enum_item"
hir_kind = "Scope"
block_kind = "Enum"

[[nodes]]
ts_name = "enum_variant_list"

[[nodes]]
ts_name = "associated_type"

[[nodes]]
ts_name = "type_item"

[[nodes]]
ts_name = "type_parameter"

[[nodes]]
ts_name = "enum_variant"
hir_kind = "Identifier"

[[nodes]]
ts_name = "impl_item"
hir_kind = "Scope"
block_kind = "Impl"

[[nodes]]
ts_name = "trait_item"
hir_kind = "Scope"
block_kind = "Scope"

[[nodes]]
ts_name = "const_item"
hir_kind = "Scope"
block_kind = "Const"

[[nodes]]
ts_name = "static_item"
hir_kind = "Scope"
block_kind = "Const"

[[nodes]]
ts_name = "function_item"
hir_kind = "Scope"
block_kind = "Func"

[[nodes]]
ts_name = "function_signature_item"
hir_kind = "Scope"
block_kind = "Func"

[[nodes]]
ts_name = "mutable_specifier"
hir_kind = "Text"

[[nodes]]
ts_name = "expression_statement"

[[nodes]]
ts_name = "assignment_expression"

[[nodes]]
ts_name = "binary_expression"

[[nodes]]
ts_name = "operator"
hir_kind = "Internal"
named = false

[[nodes]]
ts_name = "call_expression"
block_kind = "Call"

[[nodes]]
ts_name = "macro_invocation"
block_kind = "Call"

[[nodes]]
ts_name = "macro_definition"
hir_kind = "Scope"
block_kind = "Func"

[[nodes]]
ts_name = "arguments"

[[nodes]]
ts_name = "primitive_type"
hir_kind = "Identifier"

[[fields]]
name = "field_name"
field_name = "name"

[[fields]]
name = "field_type"
field_name = "type"

[[fields]]
name = "field_pattern"
field_name = "pattern"

[[fields]]
name = "field_return_type"
field_name = "return_type"

[[fields]]
name = "field_parameters"
field_name = "parameters"


[[fields]]
name = "field_bounds"
field_name = "bounds"

[[fields]]
name = "field_default_type"
field_name = "default_type"

[[fields]]
name = "field_macro"
field_name = "macro"
