default_hir_kind = "Internal"

[[text_tokens]]
name = "Text_fn"
literal = "fn"
hir_kind = "Text"

[[text_tokens]]
name = "Text_LPAREN"
literal = "("
hir_kind = "Text"

[[text_tokens]]
name = "Text_RPAREN"
literal = ")"
hir_kind = "Text"

[[text_tokens]]
name = "Text_LBRACE"
literal = "{"
hir_kind = "Text"

[[text_tokens]]
name = "Text_RBRACE"
literal = "}"
hir_kind = "Text"

[[text_tokens]]
name = "Text_let"
literal = "let"
hir_kind = "Text"

[[text_tokens]]
name = "Text_EQ"
literal = "="
hir_kind = "Text"

[[text_tokens]]
name = "Text_SEMI"
literal = ";"
hir_kind = "Text"

[[text_tokens]]
name = "Text_COLON"
literal = ":"
hir_kind = "Text"

[[text_tokens]]
name = "Text_COMMA"
literal = ","
hir_kind = "Text"

[[text_tokens]]
name = "Text_ARROW"
literal = "->"
hir_kind = "Text"

[[text_tokens]]
name = "Text_EQEQ"
literal = "=="
hir_kind = "Text"

[[text_tokens]]
name = "Text_NE"
literal = "!="
hir_kind = "Text"

[[text_tokens]]
name = "Text_LT"
literal = "<"
hir_kind = "Text"

[[text_tokens]]
name = "Text_GT"
literal = ">"
hir_kind = "Text"

[[text_tokens]]
name = "Text_LE"
literal = "<="
hir_kind = "Text"

[[text_tokens]]
name = "Text_GE"
literal = ">="
hir_kind = "Text"

[[text_tokens]]
name = "Text_AMPAMP"
literal = "&&"
hir_kind = "Text"

[[text_tokens]]
name = "Text_PIPEPIPE"
literal = "||"
hir_kind = "Text"

[[text_tokens]]
name = "Text_PLUS"
literal = "+"
hir_kind = "Text"

[[text_tokens]]
name = "Text_MINUS"
literal = "-"
hir_kind = "Text"

[[text_tokens]]
name = "Text_STAR"
literal = "*"
hir_kind = "Text"

[[text_tokens]]
name = "Text_SLASH"
literal = "/"
hir_kind = "Text"

[[text_tokens]]
name = "Text_PERCENT"
literal = "%"
hir_kind = "Text"

[[nodes]]
ts_name = "integer_literal"
# hir_kind = "Text"

[[nodes]]
ts_name = "float_literal"
# hir_kind = "Text"

[[nodes]]
ts_name = "string_literal"
# hir_kind = "Text"

[[nodes]]
ts_name = "boolean_literal"
# hir_kind = "Text"

[[nodes]]
ts_name = "char_literal"
# hir_kind = "Text"

[[nodes]]
ts_name = "type_identifier"
hir_kind = "Identifier"

[[nodes]]
ts_name = "scoped_identifier"
hir_kind = "Internal"

[[nodes]]
ts_name = "scoped_type_identifier"
hir_kind = "Internal"

[[nodes]]
ts_name = "field_identifier"
hir_kind = "Identifier"

[[nodes]]
ts_name = "shorthand_field_identifier"
hir_kind = "Identifier"

[[nodes]]
ts_name = "identifier"
hir_kind = "Identifier"


[[nodes]]
ts_name = "ordered_field_declaration_list"

[[nodes]]
ts_name = "parameter"
block_kind = "Parameter"

[[nodes]]
ts_name = "self_parameter"
name = "self_param"
block_kind = "Parameter"
hir_kind = "Scope"

[[nodes]]
ts_name = "self"
name = "self_keyword"
hir_kind = "Identifier"

[[nodes]]
ts_name = "parameters"
# Container node, not a block itself - individual parameters are blocks

[[nodes]]
ts_name = "let_declaration"

[[nodes]]
ts_name = "visibility_modifier"
hir_kind = "Text"

[[nodes]]
ts_name = "field_declaration"
block_kind = "Field"

[[nodes]]
ts_name = "block"
hir_kind = "Scope"
block_kind = "Scope"

[[nodes]]
ts_name = "source_file"
hir_kind = "Scope"
block_kind = "Root"

[[nodes]]
ts_name = "mod_item"
hir_kind = "Scope"
block_kind = "Scope"

[[nodes]]
ts_name = "struct_item"
hir_kind = "Scope"
block_kind = "Class"

[[nodes]]
ts_name = "enum_item"
hir_kind = "Scope"
block_kind = "Enum"

[[nodes]]
ts_name = "enum_variant_list"

[[nodes]]
ts_name = "associated_type"
hir_kind = "Scope"
block_kind = "Alias"

[[nodes]]
ts_name = "type_item"
hir_kind = "Scope"
block_kind = "Alias"

[[nodes]]
ts_name = "array_type"
hir_kind = "Scope"

[[nodes]]
ts_name = "tuple_type"
hir_kind = "Scope"

[[nodes]]
ts_name = "abstract_type"

[[nodes]]
ts_name = "bounded_type"

[[nodes]]
ts_name = "trait_bounds"

[[nodes]]
ts_name = "lifetime"

[[nodes]]
ts_name = "function_type"

[[nodes]]
ts_name = "reference_type"

[[nodes]]
ts_name = "pointer_type"

[[nodes]]
ts_name = "generic_type"

[[nodes]]
ts_name = "tuple_pattern"

[[nodes]]
ts_name = "struct_pattern"

[[nodes]]
ts_name = "or_pattern"

[[nodes]]
ts_name = "slice_pattern"


[[nodes]]
ts_name = "reference_pattern"

[[nodes]]
ts_name = "mut_pattern"

[[nodes]]
ts_name = "ref_pattern"

[[nodes]]
ts_name = "text_node"

[[nodes]]
ts_name = "generic_type_with_turbofish"

[[nodes]]
ts_name = "index_expression"

[[nodes]]
ts_name = "type_cast_expression"

[[nodes]]
ts_name = "type_parameter"

[[nodes]]
ts_name = "const_parameter"

[[nodes]]
ts_name = "where_clause"

[[nodes]]
ts_name = "where_predicate"

[[nodes]]
ts_name = "enum_variant"
hir_kind = "Scope"
block_kind = "Field"

[[nodes]]
ts_name = "impl_item"
hir_kind = "Scope"
block_kind = "Impl"

[[nodes]]
ts_name = "trait_item"
hir_kind = "Scope"
block_kind = "Trait"

[[nodes]]
ts_name = "const_item"
hir_kind = "Scope"
block_kind = "Const"

[[nodes]]
ts_name = "static_item"
hir_kind = "Scope"
block_kind = "Const"

[[nodes]]
ts_name = "function_item"
hir_kind = "Scope"
block_kind = "Func"

[[nodes]]
ts_name = "function_signature_item"
hir_kind = "Scope"
block_kind = "Func"

[[nodes]]
ts_name = "mutable_specifier"
hir_kind = "Text"

[[nodes]]
ts_name = "expression_statement"

[[nodes]]
ts_name = "assignment_expression"

[[nodes]]
ts_name = "binary_expression"

[[nodes]]
ts_name = "operator"
hir_kind = "Internal"
named = false

[[nodes]]
ts_name = "call_expression"
block_kind = "Call"

[[nodes]]
ts_name = "reference_expression"

[[nodes]]
ts_name = "field_expression"

[[nodes]]
ts_name = "try_expression"

[[nodes]]
ts_name = "await_expression"

[[nodes]]
ts_name = "parenthesized_expression"

[[nodes]]
ts_name = "macro_invocation"
block_kind = "Call"

[[nodes]]
ts_name = "macro_definition"
hir_kind = "Scope"
block_kind = "Func"

[[nodes]]
ts_name = "arguments"

[[nodes]]
ts_name = "primitive_type"
hir_kind = "Identifier"

[[nodes]]
ts_name = "struct_expression"

[[nodes]]
ts_name = "if_expression"

[[nodes]]
ts_name = "match_expression"

[[nodes]]
ts_name = "match_block"
hir_kind = "Scope"

[[nodes]]
ts_name = "while_expression"

[[nodes]]
ts_name = "loop_expression"

[[nodes]]
ts_name = "for_expression"

[[nodes]]
ts_name = "array_expression"

[[nodes]]
ts_name = "tuple_expression"

[[nodes]]
ts_name = "unit_expression"

[[nodes]]
ts_name = "range_expression"

[[nodes]]
ts_name = "unary_expression"

[[nodes]]
ts_name = "tuple_struct_pattern"
hir_kind = "Internal"

[[nodes]]
ts_name = "closure_expression"
hir_kind = "Scope"
block_kind = "Closure"

[[nodes]]
ts_name = "closure_parameters"

[[nodes]]
ts_name = "super"
name = "super_token"
hir_kind = "Identifier"

[[nodes]]
ts_name = "crate"
name = "crate_token"
hir_kind = "Identifier"

[[fields]]
name = "field_name"
field_name = "name"

[[fields]]
name = "field_type"
field_name = "type"

[[fields]]
name = "field_pattern"
field_name = "pattern"

[[fields]]
name = "field_return_type"
field_name = "return_type"
block_kind = "Return"

[[fields]]
name = "field_parameters"
field_name = "parameters"


[[fields]]
name = "field_bounds"
field_name = "bounds"

[[fields]]
name = "field_default_type"
field_name = "default_type"

[[fields]]
name = "field_macro"
field_name = "macro"


[[fields]]
name = "field_body"
field_name = "body"

[[fields]]
name = "field_left"
field_name = "left"

[[fields]]
name = "field_right"
field_name = "right"

[[fields]]
name = "field_operator"
field_name = "operator"

[[fields]]
name = "field_function"
field_name = "function"

[[fields]]
name = "field_arguments"
field_name = "arguments"

[[fields]]
name = "field_type_arguments"
field_name = "type_arguments"

[[fields]]
name = "field_value"
field_name = "value"

[[fields]]
name = "field_field"
field_name = "field"

[[fields]]
name = "field_trait"
field_name = "trait"

[[fields]]
name = "field_element"
field_name = "element"

[[fields]]
name = "field_length"
field_name = "length"

[[fields]]
name = "field_consequence"
field_name = "consequence"

[[fields]]
name = "field_argument"
field_name = "argument"

[[fields]]
name = "field_condition"
field_name = "condition"

[[fields]]
name = "field_path"
field_name = "path"