[package]
name = "llmcc-simple"
version = "0.2.50"
edition = "2021"
authors = ["llmcc contributors"]

[dependencies]
llmcc-core = { path = "../llmcc-core", version = "0.2.50" }
paste = "1.0"

[dev-dependencies]
